[project]
name = "llm-worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "llama-cpp-python>=0.3.9",
    "loguru>=0.7.3",
    "redis>=6.1.0",
]
